import { useState } from 'react';
import { Webhook, Send, CheckCircle, XCircle, Copy, ExternalLink, AlertCircle } from 'lucide-react';
import { projectId, publicAnonKey } from '/utils/supabase/info';

export default function WebhookTest() {
  const [testPayload, setTestPayload] = useState({
    reference: 'GRIDOS-1710611234567-TEST01',
    transaction_id: 'CP-TXN-TEST-123456',
    status: 'success',
    amount: 5050,
    currency: 'TZS',
    provider: 'MPESA',
    phone: '+255712345678',
    timestamp: new Date().toISOString()
  });
  
  const [signature, setSignature] = useState('');
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const WEBHOOK_URL = `https://${projectId}.supabase.co/functions/v1/make-server-4719aee2/webhooks/clickpesa/callback`;
  const API_URL = `https://${projectId}.supabase.co/functions/v1/make-server-4719aee2`;

  const copyWebhookUrl = () => {
    navigator.clipboard.writeText(WEBHOOK_URL);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const generateTestSignature = async () => {
    // In production, this would be generated by ClickPesa
    // For testing, we'll use a mock signature
    const mockSignature = Array.from(
      { length: 64 }, 
      () => Math.floor(Math.random() * 16).toString(16)
    ).join('');
    setSignature(mockSignature);
    return mockSignature;
  };

  const testWebhook = async () => {
    setLoading(true);
    setResult(null);

    try {
      // Generate test signature if not provided
      const testSig = signature || await generateTestSignature();

      const response = await fetch(WEBHOOK_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-Signature': testSig,
          'Authorization': `Bearer ${publicAnonKey}`
        },
        body: JSON.stringify(testPayload)
      });

      const data = await response.json();

      setResult({
        status: response.ok ? 'success' : 'error',
        statusCode: response.status,
        data
      });
    } catch (error) {
      setResult({
        status: 'error',
        error: error instanceof Error ? error.message : 'Network error'
      });
    } finally {
      setLoading(false);
    }
  };

  const updatePayload = (field: string, value: any) => {
    setTestPayload(prev => ({ ...prev, [field]: value }));
  };

  return (
    <div className="p-8 space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold flex items-center gap-3" style={{ color: 'var(--text-primary)' }}>
          <Webhook className="w-7 h-7" style={{ color: 'var(--brand-emerald)' }} />
          ClickPesa Webhook Testing
        </h1>
        <p className="mt-1" style={{ color: 'var(--text-muted)', fontSize: 'var(--text-body)' }}>
          Test and debug webhook callbacks from ClickPesa payment gateway
        </p>
      </div>

      {/* Webhook URL Card */}
      <div className="rounded-lg border p-6 space-y-4" style={{
        backgroundColor: 'var(--bg-card)',
        borderColor: 'var(--bg-border-subtle)'
      }}>
        <h2 className="font-semibold text-lg" style={{ color: 'var(--text-primary)' }}>
          Your Webhook URL
        </h2>
        
        <div className="flex items-center gap-3">
          <code className="flex-1 px-4 py-3 rounded-lg text-sm" style={{
            backgroundColor: 'var(--bg-surface)',
            borderWidth: '1px',
            borderStyle: 'solid',
            borderColor: 'var(--bg-border-subtle)',
            color: 'var(--text-primary)',
            fontFamily: 'monospace'
          }}>
            {WEBHOOK_URL}
          </code>
          <button
            onClick={copyWebhookUrl}
            className="px-4 py-3 rounded-lg border transition-colors flex items-center gap-2"
            style={{
              backgroundColor: 'var(--bg-surface)',
              borderColor: 'var(--bg-border-subtle)',
              color: 'var(--text-primary)'
            }}
          >
            {copied ? <CheckCircle className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied!' : 'Copy'}
          </button>
        </div>

        {/* Configuration Instructions */}
        <div className="rounded-lg border p-4 space-y-3" style={{
          backgroundColor: 'rgba(0, 217, 126, 0.1)',
          borderColor: 'rgba(0, 217, 126, 0.3)'
        }}>
          <div className="flex items-start gap-3">
            <AlertCircle className="w-5 h-5 mt-0.5" style={{ color: 'var(--brand-emerald)' }} />
            <div className="flex-1">
              <div className="font-medium mb-2" style={{ color: 'var(--brand-emerald)' }}>
                Configure in ClickPesa Dashboard
              </div>
              <ol className="text-sm space-y-1" style={{ color: 'var(--text-muted)', listStyle: 'decimal', paddingLeft: '1.5rem' }}>
                <li>Log in to <a href="https://clickpesa.com/dashboard" target="_blank" rel="noopener noreferrer" className="underline">ClickPesa Dashboard</a></li>
                <li>Navigate to <strong>Settings → Webhooks</strong></li>
                <li>Click <strong>Add Webhook</strong></li>
                <li>Paste the URL above</li>
                <li>Select events: <code>payment.success</code>, <code>payment.failed</code>, <code>payment.cancelled</code></li>
                <li>Click <strong>Save</strong> and verify</li>
              </ol>
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-6">
        {/* Test Payload Editor */}
        <div className="rounded-lg border p-6 space-y-4" style={{
          backgroundColor: 'var(--bg-card)',
          borderColor: 'var(--bg-border-subtle)'
        }}>
          <h2 className="font-semibold text-lg" style={{ color: 'var(--text-primary)' }}>
            Test Webhook Payload
          </h2>

          {/* Reference */}
          <div>
            <label className="block text-sm font-medium mb-2" style={{ color: 'var(--text-muted)' }}>
              Reference
            </label>
            <input
              type="text"
              value={testPayload.reference}
              onChange={(e) => updatePayload('reference', e.target.value)}
              className="w-full px-4 py-2 rounded-lg border"
              style={{
                backgroundColor: 'var(--bg-surface)',
                borderColor: 'var(--bg-border-subtle)',
                color: 'var(--text-primary)'
              }}
            />
          </div>

          {/* Transaction ID */}
          <div>
            <label className="block text-sm font-medium mb-2" style={{ color: 'var(--text-muted)' }}>
              Transaction ID
            </label>
            <input
              type="text"
              value={testPayload.transaction_id}
              onChange={(e) => updatePayload('transaction_id', e.target.value)}
              className="w-full px-4 py-2 rounded-lg border"
              style={{
                backgroundColor: 'var(--bg-surface)',
                borderColor: 'var(--bg-border-subtle)',
                color: 'var(--text-primary)'
              }}
            />
          </div>

          {/* Status */}
          <div>
            <label className="block text-sm font-medium mb-2" style={{ color: 'var(--text-muted)' }}>
              Status
            </label>
            <select
              value={testPayload.status}
              onChange={(e) => updatePayload('status', e.target.value)}
              className="w-full px-4 py-2 rounded-lg border"
              style={{
                backgroundColor: 'var(--bg-surface)',
                borderColor: 'var(--bg-border-subtle)',
                color: 'var(--text-primary)'
              }}
            >
              <option value="success">success</option>
              <option value="completed">completed</option>
              <option value="failed">failed</option>
              <option value="cancelled">cancelled</option>
              <option value="pending">pending</option>
            </select>
          </div>

          {/* Amount */}
          <div>
            <label className="block text-sm font-medium mb-2" style={{ color: 'var(--text-muted)' }}>
              Amount (TZS)
            </label>
            <input
              type="number"
              value={testPayload.amount}
              onChange={(e) => updatePayload('amount', parseInt(e.target.value))}
              className="w-full px-4 py-2 rounded-lg border"
              style={{
                backgroundColor: 'var(--bg-surface)',
                borderColor: 'var(--bg-border-subtle)',
                color: 'var(--text-primary)'
              }}
            />
          </div>

          {/* Provider */}
          <div>
            <label className="block text-sm font-medium mb-2" style={{ color: 'var(--text-muted)' }}>
              Provider
            </label>
            <select
              value={testPayload.provider}
              onChange={(e) => updatePayload('provider', e.target.value)}
              className="w-full px-4 py-2 rounded-lg border"
              style={{
                backgroundColor: 'var(--bg-surface)',
                borderColor: 'var(--bg-border-subtle)',
                color: 'var(--text-primary)'
              }}
            >
              <option value="MPESA">M-Pesa</option>
              <option value="AIRTEL">Airtel Money</option>
              <option value="TIGO">Tigo Pesa</option>
              <option value="HALOPESA">Halopesa</option>
            </select>
          </div>

          {/* Phone */}
          <div>
            <label className="block text-sm font-medium mb-2" style={{ color: 'var(--text-muted)' }}>
              Phone Number
            </label>
            <input
              type="tel"
              value={testPayload.phone}
              onChange={(e) => updatePayload('phone', e.target.value)}
              className="w-full px-4 py-2 rounded-lg border"
              style={{
                backgroundColor: 'var(--bg-surface)',
                borderColor: 'var(--bg-border-subtle)',
                color: 'var(--text-primary)'
              }}
            />
          </div>

          {/* Signature (Optional) */}
          <div>
            <label className="block text-sm font-medium mb-2" style={{ color: 'var(--text-muted)' }}>
              X-Signature (Optional - auto-generated if empty)
            </label>
            <input
              type="text"
              value={signature}
              onChange={(e) => setSignature(e.target.value)}
              placeholder="Leave empty for mock signature"
              className="w-full px-4 py-2 rounded-lg border"
              style={{
                backgroundColor: 'var(--bg-surface)',
                borderColor: 'var(--bg-border-subtle)',
                color: 'var(--text-primary)'
              }}
            />
          </div>

          {/* Send Button */}
          <button
            onClick={testWebhook}
            disabled={loading}
            className="w-full px-6 py-3 rounded-lg font-medium transition-colors flex items-center justify-center gap-2"
            style={{
              backgroundColor: loading ? 'var(--bg-surface)' : 'var(--brand-emerald)',
              color: loading ? 'var(--text-muted)' : '#ffffff',
              cursor: loading ? 'not-allowed' : 'pointer'
            }}
          >
            {loading ? (
              <>
                <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                Sending Webhook...
              </>
            ) : (
              <>
                <Send className="w-5 h-5" />
                Send Test Webhook
              </>
            )}
          </button>
        </div>

        {/* Response */}
        <div className="rounded-lg border p-6 space-y-4" style={{
          backgroundColor: 'var(--bg-card)',
          borderColor: 'var(--bg-border-subtle)'
        }}>
          <h2 className="font-semibold text-lg" style={{ color: 'var(--text-primary)' }}>
            Webhook Response
          </h2>

          {result ? (
            <div className="space-y-4">
              {/* Status Badge */}
              <div className="flex items-center gap-2">
                {result.status === 'success' ? (
                  <>
                    <CheckCircle className="w-6 h-6" style={{ color: 'var(--brand-emerald)' }} />
                    <span className="font-medium text-lg" style={{ color: 'var(--brand-emerald)' }}>
                      Webhook Received Successfully
                    </span>
                  </>
                ) : (
                  <>
                    <XCircle className="w-6 h-6" style={{ color: '#E24B4A' }} />
                    <span className="font-medium text-lg" style={{ color: '#E24B4A' }}>
                      Webhook Failed
                    </span>
                  </>
                )}
              </div>

              {/* Status Code */}
              <div className="flex justify-between items-center p-3 rounded" style={{
                backgroundColor: 'var(--bg-surface)'
              }}>
                <span style={{ color: 'var(--text-muted)' }}>HTTP Status:</span>
                <code className="font-mono" style={{
                  color: result.statusCode === 200 ? 'var(--brand-emerald)' : '#E24B4A'
                }}>
                  {result.statusCode}
                </code>
              </div>

              {/* Response Body */}
              <div>
                <div className="text-sm font-medium mb-2" style={{ color: 'var(--text-muted)' }}>
                  Response Body:
                </div>
                <pre className="p-4 rounded-lg overflow-x-auto text-xs" style={{
                  backgroundColor: 'var(--bg-surface)',
                  borderWidth: '1px',
                  borderStyle: 'solid',
                  borderColor: 'var(--bg-border-subtle)',
                  color: 'var(--text-primary)',
                  fontFamily: 'monospace'
                }}>
{JSON.stringify(result.data || result.error, null, 2)}
                </pre>
              </div>

              {/* What Happened */}
              {result.status === 'success' && (
                <div className="rounded-lg border p-4" style={{
                  backgroundColor: 'rgba(0, 217, 126, 0.1)',
                  borderColor: 'rgba(0, 217, 126, 0.3)'
                }}>
                  <div className="text-sm font-medium mb-2" style={{ color: 'var(--brand-emerald)' }}>
                    ✅ What Happened:
                  </div>
                  <ul className="text-sm space-y-1" style={{ color: 'var(--text-muted)', listStyle: 'disc', paddingLeft: '1.5rem' }}>
                    <li>Webhook signature verified</li>
                    <li>Payment record updated in database</li>
                    {testPayload.status === 'success' && (
                      <>
                        <li>Customer balance credited</li>
                        <li>STS token generated (20 digits)</li>
                        <li>Transaction logged for audit</li>
                      </>
                    )}
                  </ul>
                </div>
              )}
            </div>
          ) : (
            <div className="text-center py-12" style={{ color: 'var(--text-faint)' }}>
              <Webhook className="w-12 h-12 mx-auto mb-3" style={{ opacity: 0.3 }} />
              <div className="text-sm">No webhook sent yet</div>
              <div className="text-xs mt-1">Configure the payload and click "Send Test Webhook"</div>
            </div>
          )}
        </div>
      </div>

      {/* Webhook Events Reference */}
      <div className="rounded-lg border p-6 space-y-4" style={{
        backgroundColor: 'var(--bg-card)',
        borderColor: 'var(--bg-border-subtle)'
      }}>
        <h3 className="font-semibold text-lg" style={{ color: 'var(--text-primary)' }}>
          Webhook Events Reference
        </h3>

        <div className="grid grid-cols-3 gap-4">
          <div className="p-4 rounded-lg" style={{ backgroundColor: 'var(--bg-surface)' }}>
            <div className="font-medium mb-2" style={{ color: 'var(--brand-emerald)' }}>
              payment.success
            </div>
            <div className="text-sm" style={{ color: 'var(--text-muted)' }}>
              Payment completed successfully. Customer balance credited and STS token generated.
            </div>
          </div>

          <div className="p-4 rounded-lg" style={{ backgroundColor: 'var(--bg-surface)' }}>
            <div className="font-medium mb-2" style={{ color: '#E24B4A' }}>
              payment.failed
            </div>
            <div className="text-sm" style={{ color: 'var(--text-muted)' }}>
              Payment failed (insufficient funds, timeout, etc). No balance change.
            </div>
          </div>

          <div className="p-4 rounded-lg" style={{ backgroundColor: 'var(--bg-surface)' }}>
            <div className="font-medium mb-2" style={{ color: '#EF9F27' }}>
              payment.cancelled
            </div>
            <div className="text-sm" style={{ color: 'var(--text-muted)' }}>
              Customer cancelled payment. No balance change.
            </div>
          </div>
        </div>
      </div>

      {/* Documentation Link */}
      <div className="text-center text-sm" style={{ color: 'var(--text-faint)' }}>
        Full webhook documentation: <a href="/CLICKPESA_INTEGRATION.md" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--brand-emerald)', textDecoration: 'underline' }}>CLICKPESA_INTEGRATION.md</a>
      </div>
    </div>
  );
}
